// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using comaagora.Data;

#nullable disable

namespace comaagora.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212014252_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CategoriasProdutoProduto", b =>
                {
                    b.Property<ulong>("CategoriaId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ProdutosId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("CategoriaId", "ProdutosId");

                    b.HasIndex("ProdutosId");

                    b.ToTable("CategoriasProdutoProduto");
                });

            modelBuilder.Entity("comaagora.Models.Assinatura", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("ClienteSaasId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DadosPagamento")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataTermino")
                        .HasColumnType("date");

                    b.Property<ulong?>("PlanoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteSaasId");

                    b.HasIndex("PlanoId");

                    b.ToTable("Assinatura");
                });

            modelBuilder.Entity("comaagora.Models.Auditorium", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong?>("ClienteSaasId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DadosJson")
                        .HasColumnType("longtext");

                    b.Property<string>("RegistroId")
                        .HasColumnType("longtext");

                    b.Property<string>("TabelaNome")
                        .HasColumnType("longtext");

                    b.Property<ulong?>("UsuarioId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ClienteSaasId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditorium");
                });

            modelBuilder.Entity("comaagora.Models.CategoriasProduto", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("ClienteSaasId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("EstabelecimentoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteSaasId");

                    b.HasIndex("EstabelecimentoId");

                    b.ToTable("CategoriasProduto");
                });

            modelBuilder.Entity("comaagora.Models.Cliente", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("ClienteSaasId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteSaasId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("comaagora.Models.ClientesSaa", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong?>("PlanoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId");

                    b.ToTable("ClientesSaa");
                });

            modelBuilder.Entity("comaagora.Models.EnderecosCliente", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<ulong>("ClienteId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Referencia")
                        .HasColumnType("longtext");

                    b.Property<string>("Rua")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("EnderecosCliente");
                });

            modelBuilder.Entity("comaagora.Models.Entrega", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("EntregadorId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime?>("FinalizadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("IniciadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("PedidoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EntregadorId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Entrega");
                });

            modelBuilder.Entity("comaagora.Models.Entregadore", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool?>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("ClienteSaasId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Veiculo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteSaasId");

                    b.ToTable("Entregadore");
                });

            modelBuilder.Entity("comaagora.Models.Estabelecimento", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<ulong>("ClienteSaasId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("PublicSlug")
                        .HasColumnType("longtext");

                    b.Property<string>("PublicToken")
                        .HasColumnType("longtext");

                    b.Property<ulong?>("ResponsavelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteSaasId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Estabelecimento");
                });

            modelBuilder.Entity("comaagora.Models.Pagamento", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DadosTransacao")
                        .HasColumnType("longtext");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("longtext");

                    b.Property<ulong>("PedidoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("comaagora.Models.Pedido", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("ClienteId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ClienteSaasId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("CodigoExterno")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("EnderecoEntregaId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("EstabelecimentoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("MetodoPagamento")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorSubtotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ClienteSaasId");

                    b.HasIndex("EnderecoEntregaId");

                    b.HasIndex("EstabelecimentoId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("comaagora.Models.PedidoIten", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Adicionais")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("PedidoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<ulong?>("ProdutoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalItem")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("PedidoIten");
                });

            modelBuilder.Entity("comaagora.Models.Plano", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LimiteEstabelecimentos")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecoMensal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Recursos")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Plano");
                });

            modelBuilder.Entity("comaagora.Models.Produto", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool?>("AceitaAdicionais")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("ClienteSaasId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("CriadoPor")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("CriadoPorNavigationId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<ulong>("EstabelecimentoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int?>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PrecoPromocional")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Sku")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Unidade")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteSaasId");

                    b.HasIndex("CriadoPorNavigationId");

                    b.HasIndex("EstabelecimentoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("comaagora.Models.ProdutoImagen", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<ulong>("ProdutoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoImagen");
                });

            modelBuilder.Entity("comaagora.Models.Setting", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("ClienteSaasId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Dados")
                        .HasColumnType("longtext");

                    b.Property<ulong?>("EstabelecimentoId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Valor")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteSaasId");

                    b.HasIndex("EstabelecimentoId");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("comaagora.Models.Usuario", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool?>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("ClienteSaasId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteSaasId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CategoriasProdutoProduto", b =>
                {
                    b.HasOne("comaagora.Models.CategoriasProduto", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comaagora.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("comaagora.Models.Assinatura", b =>
                {
                    b.HasOne("comaagora.Models.ClientesSaa", "ClienteSaas")
                        .WithMany("Assinaturas")
                        .HasForeignKey("ClienteSaasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comaagora.Models.Plano", "Plano")
                        .WithMany("Assinaturas")
                        .HasForeignKey("PlanoId");

                    b.Navigation("ClienteSaas");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("comaagora.Models.Auditorium", b =>
                {
                    b.HasOne("comaagora.Models.ClientesSaa", "ClienteSaas")
                        .WithMany("Auditoria")
                        .HasForeignKey("ClienteSaasId");

                    b.HasOne("comaagora.Models.Usuario", "Usuario")
                        .WithMany("Auditoria")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("ClienteSaas");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("comaagora.Models.CategoriasProduto", b =>
                {
                    b.HasOne("comaagora.Models.ClientesSaa", "ClienteSaas")
                        .WithMany("CategoriasProdutos")
                        .HasForeignKey("ClienteSaasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comaagora.Models.Estabelecimento", "Estabelecimento")
                        .WithMany("CategoriasProdutos")
                        .HasForeignKey("EstabelecimentoId");

                    b.Navigation("ClienteSaas");

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("comaagora.Models.Cliente", b =>
                {
                    b.HasOne("comaagora.Models.ClientesSaa", "ClienteSaas")
                        .WithMany("Clientes")
                        .HasForeignKey("ClienteSaasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteSaas");
                });

            modelBuilder.Entity("comaagora.Models.ClientesSaa", b =>
                {
                    b.HasOne("comaagora.Models.Plano", "Plano")
                        .WithMany("ClientesSaas")
                        .HasForeignKey("PlanoId");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("comaagora.Models.EnderecosCliente", b =>
                {
                    b.HasOne("comaagora.Models.Cliente", "Cliente")
                        .WithMany("EnderecosClientes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("comaagora.Models.Entrega", b =>
                {
                    b.HasOne("comaagora.Models.Entregadore", "Entregador")
                        .WithMany("Entregas")
                        .HasForeignKey("EntregadorId");

                    b.HasOne("comaagora.Models.Pedido", "Pedido")
                        .WithMany("Entregas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entregador");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("comaagora.Models.Entregadore", b =>
                {
                    b.HasOne("comaagora.Models.ClientesSaa", "ClienteSaas")
                        .WithMany("Entregadores")
                        .HasForeignKey("ClienteSaasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteSaas");
                });

            modelBuilder.Entity("comaagora.Models.Estabelecimento", b =>
                {
                    b.HasOne("comaagora.Models.ClientesSaa", "ClienteSaas")
                        .WithMany("Estabelecimentos")
                        .HasForeignKey("ClienteSaasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comaagora.Models.Usuario", "Responsavel")
                        .WithMany("Estabelecimentos")
                        .HasForeignKey("ResponsavelId");

                    b.Navigation("ClienteSaas");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("comaagora.Models.Pagamento", b =>
                {
                    b.HasOne("comaagora.Models.Pedido", "Pedido")
                        .WithMany("Pagamentos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("comaagora.Models.Pedido", b =>
                {
                    b.HasOne("comaagora.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comaagora.Models.ClientesSaa", "ClienteSaas")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteSaasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comaagora.Models.EnderecosCliente", "EnderecoEntrega")
                        .WithMany("Pedidos")
                        .HasForeignKey("EnderecoEntregaId");

                    b.HasOne("comaagora.Models.Estabelecimento", "Estabelecimento")
                        .WithMany("Pedidos")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ClienteSaas");

                    b.Navigation("EnderecoEntrega");

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("comaagora.Models.PedidoIten", b =>
                {
                    b.HasOne("comaagora.Models.Pedido", "Pedido")
                        .WithMany("PedidoItens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comaagora.Models.Produto", "Produto")
                        .WithMany("PedidoItens")
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("comaagora.Models.Produto", b =>
                {
                    b.HasOne("comaagora.Models.ClientesSaa", "ClienteSaas")
                        .WithMany("Produtos")
                        .HasForeignKey("ClienteSaasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comaagora.Models.Usuario", "CriadoPorNavigation")
                        .WithMany("Produtos")
                        .HasForeignKey("CriadoPorNavigationId");

                    b.HasOne("comaagora.Models.Estabelecimento", "Estabelecimento")
                        .WithMany("Produtos")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteSaas");

                    b.Navigation("CriadoPorNavigation");

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("comaagora.Models.ProdutoImagen", b =>
                {
                    b.HasOne("comaagora.Models.Produto", "Produto")
                        .WithMany("ProdutoImagens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("comaagora.Models.Setting", b =>
                {
                    b.HasOne("comaagora.Models.ClientesSaa", "ClienteSaas")
                        .WithMany("Settings")
                        .HasForeignKey("ClienteSaasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comaagora.Models.Estabelecimento", "Estabelecimento")
                        .WithMany("Settings")
                        .HasForeignKey("EstabelecimentoId");

                    b.Navigation("ClienteSaas");

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("comaagora.Models.Usuario", b =>
                {
                    b.HasOne("comaagora.Models.ClientesSaa", "ClienteSaas")
                        .WithMany("Usuarios")
                        .HasForeignKey("ClienteSaasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteSaas");
                });

            modelBuilder.Entity("comaagora.Models.Cliente", b =>
                {
                    b.Navigation("EnderecosClientes");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("comaagora.Models.ClientesSaa", b =>
                {
                    b.Navigation("Assinaturas");

                    b.Navigation("Auditoria");

                    b.Navigation("CategoriasProdutos");

                    b.Navigation("Clientes");

                    b.Navigation("Entregadores");

                    b.Navigation("Estabelecimentos");

                    b.Navigation("Pedidos");

                    b.Navigation("Produtos");

                    b.Navigation("Settings");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("comaagora.Models.EnderecosCliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("comaagora.Models.Entregadore", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("comaagora.Models.Estabelecimento", b =>
                {
                    b.Navigation("CategoriasProdutos");

                    b.Navigation("Pedidos");

                    b.Navigation("Produtos");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("comaagora.Models.Pedido", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("Pagamentos");

                    b.Navigation("PedidoItens");
                });

            modelBuilder.Entity("comaagora.Models.Plano", b =>
                {
                    b.Navigation("Assinaturas");

                    b.Navigation("ClientesSaas");
                });

            modelBuilder.Entity("comaagora.Models.Produto", b =>
                {
                    b.Navigation("PedidoItens");

                    b.Navigation("ProdutoImagens");
                });

            modelBuilder.Entity("comaagora.Models.Usuario", b =>
                {
                    b.Navigation("Auditoria");

                    b.Navigation("Estabelecimentos");

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
